### ISSUE TITLE
Signature checking broken

### ISSUE THREAD

**Issue by betelgeuse** [cardinalblue/rest-graph#1]
<pre>
[130, 139] in /Library/Ruby/Gems/1.8/gems/rest-graph-1.2.0/lib/rest-graph.rb
   130    def parse_cookies! cookies
   131      self.data = parse_fbs!(cookies["fbs_#{app_id}"])
   132    end
   133  
   134    def parse_fbs! fbs
=> 135      self.data = fbs &&
   136        check_sig_and_return_data(Rack::Utils.parse_query(fbs[1..-2]))
   137    end
   138  
   139    def parse_json! json
/Library/Ruby/Gems/1.8/gems/rest-graph-1.2.0/lib/rest-graph.rb:135
self.data = fbs &&
(rdb:1) p fbs
"access_token=125375250818909|2.gJefVtNueJoIKQlXOGu9sg__.3600.1275411600-1780969801|JObyEBoVrMancMK72mcqVW4a0cU.&expires=1275411600&secret=w0jBkWJm0vMKSIe7JbSwbQ__&session_key=2.gJefVtNueJoIKQlXOGu9sg__.3600.1275411600-1780969801&sig=e1be9459c68bb1777947e7b9665d5c9b&uid=1780969801"
(rdb:1) p fbs[1..-2]
"ccess_token=125375250818909|2.gJefVtNueJoIKQlXOGu9sg__.3600.1275411600-1780969801|JObyEBoVrMancMK72mcqVW4a0cU.&expires=1275411600&secret=w0jBkWJm0vMKSIe7JbSwbQ__&session_key=2.gJefVtNueJoIKQlXOGu9sg__.3600.1275411600-1780969801&sig=e1be9459c68bb1777947e7b9665d5c9b&uid=178096980"
</pre>

I don't know why it's taking away the first and last characters but doesn't seem right. This is under sinatra. Here you can find the Facebook provided PHP code to match the behavior against:

http://developers.facebook.com/docs/authentication/

**Comment by godfat** [comment]
The reason to take away first and last character is because it is used for cookies, and in cookies it is something like this (in your example)

<pre>"\"access_token=125375250818909|2.gJefVtNueJoIKQlXOGu9sg__.3600.1275411600-1780969801|JObyEBoVrMancMK72mcqVW4a0cU.&expires=1275411600&secret=w0jBkWJm0vMKSIe7JbSwbQ__&session_key=2.gJefVtNueJoIKQlXOGu9sg__.3600.1275411600-1780969801&sig=e1be9459c68bb1777947e7b9665d5c9b&uid=1780969801\""</pre>


So it is supposed to take out the "quotes" there. Are you using `parse_fbs!` directly? If so I guess I should move that codes from `parse_fbs!` to `parse_cookies!`

Thanks for reporting this!

**Comment by betelgeuse** [comment]
I have this in a sinatra application:

<pre>
 @rg.parse_cookies!(request.cookies)
</pre>

**Comment by godfat** [comment]
rest-graph.rb: fix a bug in parsing cookies, see below and closed by 78397d1a525370c6328d654abf2e1c2323a6b6a5

  I think this is because facebook changed their format in cookies,
  that at first they wanted to make fbs_ be a json, so they encoded it
  with quotes. But actually it's really annoying that query string is
  encoded in a json, it made it looked like double encoded...

  So even it breaks compatibility, I think this is a good move.
  (and I guess facebook still keeps changing things, need to try hard
   to follow their pathes...)

**Comment by godfat** [comment]
Sorry, forgot to credit in the commit message. Thanks for bringing this up!
We're trying to use oauth without cookies, so didn't notice about this.
