### ISSUE TITLE
Posting photo on wall

### ISSUE THREAD

**Issue by sashazykov** [cardinalblue/rest-graph#7]
Hello,

How can I post a photo?

I have tried this code, but it doesn't work.

fb_graph.post("#{facebook_id}/photos", {
          :name => name,
          :message => message,
          :source => File.read(image_file_name)
       })

**Comment by godfat** [comment]
Hi Aleksandr,

You should not pass the binary string to rest-graph ([rest-client](https://github.com/archiloque/rest-client))
directly, rather, you should just pass the IO object (here it's File).
Then rest-client would handle everything else.

This has two reasons. First, reading the entire binary as a string
hurts performance. Second, posting binary data to HTTP server
should use multipart/form-data as Content-Type instead of regular
application/x-www-form-urlencoded.

Here's your example edited accordingly:

``` ruby
fb_graph.post("#{facebook_id}/photos", {
         :name => name,
         :message => message,
         :source => File.open(image_file_name)
      })
```

You can take a look at [rest-client](https://github.com/archiloque/rest-client) if you want to know what
does it handle for you. rest-graph is simply passing everything
to rest-client.

Let me know if this works for you, then I'll close this ticket,
thanks!

**Comment by sashazykov** [comment]
Thanks!
