### ISSUE TITLE
login not working on mac (all browsers) or IE (all OS) but works fine otherwise on Win/Lin

### ISSUE THREAD

**Issue by sperl755** [cardinalblue/rest-graph#8]
login not working on mac (all browsers) or IE (all OS) but works fine otherwise on Win/Lin.

just returns you to the login  button.

no issues with windows chrome, FF.

no issues with linux chrome, FF.

We don't know why the OS would make a difference.

**Comment by godfat** [comment]
Actually we are all using mac and it works fine for us.
At least as far as I know.

How did you setup the login? Since you mentioned
login button, I guess it's Facebook's JavaScript SDK?
If so, I would guess it's a Facebook's issue.
I am used to this kind of issues from Facebook.

Oh, but you reminded that once we have a user
can never login to our applications. I don't remember
the detail, but it's indeed a Facebook issue.
If I remember correctly, it happens on a specific
version of IE, very, very rarely. The reason is that
his IE is rejecting cookies from Facebook.

Let me know if you have any other information, thanks!
